name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m venv venv
        . ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run your tests
      run: |
        . ./venv/bin/activate
        xvfb-run pytest --headed
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: |
          test-results/